name: Ollama Pulse Ingestion

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at :00
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run ingestion
        run: |
          python scripts/ingest_official.py
          python scripts/ingest_community.py
          python scripts/ingest_tools.py
          
      - name: Aggregate data
        run: python scripts/aggregate.py
        
      - name: Mine insights
        run: python scripts/mine_insights.py

      - name: Commit and push data changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(data): hourly ingestion $(date -u '+%Y-%m-%d %H:%M UTC')" && git push)

